#!/bin/sh

export HOME=/root/yoonpro
export SHELL=`which zsh`

TMUX=`which tmux 2>&1`
if [[ -x "$TMUX" ]]
then
    tmux -S /tmp/yoonpro detach -a -s yoonpro
if [[ -f "$HOME/.tmuxp/yoonpro.yaml" ]]
then
    tmuxp load ~/.tmuxp/yoonpro.yaml
else
    tmux -2 -S /tmp/yoonpro -f /root/yoonpro/.tmux.conf new -A -s yoonpro
fi
else
EXIST=`screen -list | grep yoonpro | awk '{print $2}'`
if [ "$EXIST" = "(Attached)" ]
then
    screen -x yoonpro
else
    screen -e "^Oo" -h 20000 -R yoonpro -c $HOME/.screenrc
fi
fi

export HOME=/root
