#!/bin/sh

export HOME=HOME_PASS_HERE
export SHELL=`which zsh`

TMUX=`which tmux 2>&1`
if [[ -x "$TMUX" ]]
then
    tmux -S /tmp/ID_HERE detach -a -s ID_HERE
if [[ -f "$HOME/.tmuxp/ID_HERE.yaml" ]]
then
    tmuxp load ~/.tmuxp/ID_HERE.yaml
else
    tmux -2 -S /tmp/ID_HERE -f /root/ID_HERE/.tmux.conf new -A -s ID_HERE
fi
else
EXIST=`screen -list | grep ID_HERE | awk '{print $2}'`
if [ "$EXIST" = "(Attached)" ]
then
    screen -x ID_HERE
else
    screen -e "^Oo" -h 20000 -R ID_HERE -c $HOME/.screenrc
fi
fi

export HOME=/root
